@echo off
echo Converting all assets...

call barrier1\CONV2.BAT
call barrier2\CONV2.BAT
call build1\CONV2.BAT
call build2\CONV2.BAT
call car2\CONV2.BAT
call car3\CONV2.BAT
call sign1\CONV2.BAT
call stand\CONV2.BAT
call track\blank\CONV2.BAT
call track\grass_1\CONV2.BAT
call track\grid\CONV2.BAT
call track\line\CONV2.BAT
call track\sand_1\CONV2.BAT
call track\st_01\CONV2.BAT
call track\st_1\CONV2.BAT
call track\stone1\CONV2.BAT
call track\t_00\CONV2.BAT
call track\t_01\CONV2.BAT
call track\t_02\CONV2.BAT
call track\t_1\CONV2.BAT
call tunnel\CONV2.BAT

echo Done.